### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by optozorax** [TanTanDev/DigEscape#1] opened 2020-05-15 16:42 UTC
![изображение](https://user-images.githubusercontent.com/18114381/82074947-b5dcd280-9705-11ea-93a0-8ffe2434aa86.png)

can't fall in this position

**Comment by TanTanDev** [comment] 2020-05-16 18:20
Thank you for the issue submition!

This is actually by design, I designed this level for this to be able to happend.
You might not notice it but you are in this image standing on top of a skeleton, which is something you should learn in later levels.

I haven't nailed the level order yet, so I will keep this in mind when I update some more levels.
Hopefully the user should realize that this is a dead-end and need to find another solution.

I will increase the contrast of the skeletons and the door also, It should be more visible.


<details>unbury middle platform skeleton, fall of the ledge to the right, unbury upper platform skeleton, proceed to exit:<summary>how to solve this level *spoiler*:</summary>

**Comment by TanTanDev** [comment] 2020-05-17 12:10
Since I make commits directly to this repository, I can't reference them closing this issue,
* Add new maps and change map order: # 373689e798aeb6884924eab127a4d06cf238a6a3
* Update contrast between skeleton and doors: # 201f581e89051fb0846b92e47af11d8b986c6b98

Hopefully these makes it easier for people to advance through this level

**Closed as completed by TanTanDev** 2020-05-17 12:10 UTC
